name = input('Введите Ваше имя ')
age = input('Введите Ваш возраст ')
pets_name = input('Введите имя Вашего домашнего животного ')
lucky_number = input('Какое у Вас счастливое число? ')
print('Ваше имя - ' + name)
print('Ваш возраст - ' + age)
print('Ваше домашнее животное - ' + pets_name)
print('Ваше счастливое число - ' + lucky_number)